export const LicenseLanguaje = {
	"en-Us": {
		name: "NAME",
		lastName: "LAST NAME",
		race: "RACE",
		date: "DATE OF BIRTH",
		gender: "GENDER",
		dateAdoption: "DATE ADOPTION",
		dateIssue: "DATE ISSUE",
		country: "NATIONALITY",
		adopter1: "ADOPTER ",
		adopter2: "DATA",
		adopterName: "NAME",
		adopterLastName: "LAST NAME",
		description1:
			"This card is unique and registered in the blockchain, if you find this card write to us at: ",
		description2: "In case of loss or theft, contact: ",
		description3: "or report it at",
		copyright: "FIRULAIXCOIN - All rights reserved ©",
		hash: "REGISTER:",
	},
	"es-Es": {
		name: "NOMBRE",
		lastName: "APELLIDOS",
		race: "RAZA",
		date: "FECHA DE NACIMIENTO",
		gender: "SEXO",
		dateAdoption: "FECHA DE ADOPCIÓN",
		dateIssue: "FECHA DE VENCIMIENTO",
		country: "NACIONALIDAD",
		adopter1: "DATOS DEL ",
		adopter2: "ADOPTANTE",
		adopterName: "NOMBRE",
		adopterLastName: "APELLIDOS",
		description1:
			"Este carnet es único y registrado en blockchain, si encuentras este carnet escríbenos a: ",
		description2: "En caso de pérdida o robo comunicate a: ",
		description3: "ó reportalo en",
		copyright: "FIRULAIXCOIN - Todos los derechos reservados ©",
		hash: "REGISTRO:",
	},
};
