import { dateNow, dateStringYear } from "../../../../utils/date";


export const adopterInit = {
	_id:"",
	person:"NATURAL",
	type:"ADOPTER",
	name: "",
	secondName: "",
	lastName: "",
	mLastName: "",
	gender: "MAN",
	date: dateStringYear(18),
	address: "",
	document: "D.N.I.",
	documentNumber: "",
	phone: "",
	email: "",
	country: "",
	department: "",
	province: "",
	district: "",
	direction: "",
	idRegisteringEntity:0,
	idEntity:0,
	status: false,
};

export const petInit = {
	addressEr: "",
	userAddress: "",
	userName: "",
	adopter: "",
	adopterName: "",
	adopterLastName: "",
	dateRegistring: "",
	name: "",
	race: "",
	gender: "MALE",
	date: "",
	dateAdoption: dateNow(),
	dateIssue: dateStringYear(2, true),
	chip: "",
	chipDate: dateNow(),
	colour: "",
	image: "",
	country: "PE",
	type: "DOG",
	sterilized: "NO",
	chipFather: "",
	chipMother: "",
	pedigree: "",
};

export const petInitMethods = {
	chip: "validateString",
	gender: "validateGenderPet",
	name: "validateString",
	date: "validateDate",
	dateAdoption: "validateDate",
	type: "validateString",
	race: "validateString",
	country: "validateString",
	colour: "validateString",
	dateIssue: "validateDate",
};
