import Head from "next/head";
import Script from "next/script";
import { Provider } from "../Provider";
import { Index } from "../Index";
import "../styles/globals.css";
import { ContextProvider } from "../contexts/ContextProvider";
import { ThemeSettingsContainer } from "../components/containers/ThemeSettingsContainer";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>WAR - Plataforma de Registro</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        <link rel="icon" href="/war.ico" />
      </Head>
      <Script src="https://cdn.lordicon.com/xdjxvujz.js"></Script>
      <Provider>
        <ContextProvider>
          <Index>
            <ThemeSettingsContainer>
              <Component {...pageProps} />
            </ThemeSettingsContainer>
          </Index>
        </ContextProvider>
      </Provider>
    </>
  );
}

export default MyApp;
